# Cargo.toml
[workspace]
members = [
    # libraries
    "acpi",
    "bare_metal",
    "interrupts",
    "memory",
    "multiboot2",
    "spinlock",
    # binary tying everything together
    "learnos_kernel",
]