[package]
name = "kmem"
version = "0.1.0"
authors = ["Fabian Thorand <f.thorand@gmail.com>"]
edition = "2018"

[dependencies]
bitflags = "1.0.0"
static_assertions = "0.2.5"

bare_metal = {path = "../bare_metal"}
