[package]
name = "kmem"
version = "0.1.0"
authors = ["Fabian Thorand <f.thorand@gmail.com>"]
edition = "2018"

[dependencies]
bitflags = "1.0.4"
log = "0.4.6"
static_assertions = "0.3.1"

amd64 = {path = "../amd64"}
